# Generated by Django 5.1.1 on 2024-09-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_common', models.CharField(max_length=255)),
                ('name_official', models.CharField(max_length=255)),
                ('native_name_common', models.CharField(blank=True, max_length=255, null=True)),
                ('native_name_official', models.CharField(blank=True, max_length=255, null=True)),
                ('flags_png', models.URLField(max_length=500)),
                ('flags_svg', models.URLField(max_length=500)),
                ('flags_alt', models.TextField(blank=True, null=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('area', models.FloatField()),
                ('population', models.BigIntegerField()),
                ('timezone', models.CharField(max_length=100)),
                ('continent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, unique=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
